# Generated by Django 3.2.7 on 2021-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20211005_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='--'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
