# Generated by Django 3.2.7 on 2021-11-04 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero'),
        ),
    ]
